name: Build and Deploy Code
#push, pull_request, [push, pull_request]
# push: 
#     branches: 
#         - "main"
#         - "anotherbranch"
# pull_request:
#     branches:
#         - "test_branch"
on: [push,pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2 #actions refer to github actions 
            - name: Install python version 3.12.8
              uses: actions/setup-python@v2 
              with:
                python-version: '3.12.8' 
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install all dependencies
              run: pip install -r requirements.txt
            - name: Run the pytest scripts
              run: | 
                pip install pytest
                pytest -v -s 
